
POST http://auth.eensymachines.in/devices HTTP/1.1
Content-Type: application/json

{
    "user":"kneerunjun@gmail.com",
    "hw":"BCM2835",
    "serial":"000000007920365c",
    "model":"Raspberry Pi 3 Model B Rev 1.2"
}

#### 
# since the device also needs to be registered 
POST http://localhost/api/v1/devices HTTP/1.1
Content-Type: application/json

{
    "serial":"000000007920365c",
    "rlys":["IN1","IN2","IN3","IN4"]
}